@user1=b85182a8-68f8-4d42-b0d5-6166bf2e8284
@user2=7ad223bd-bf5e-4945-8284-3a9c81e4e7a9

@ClientId=go-backend
@ClientSecret=b0ZVXfrGkyFlgXTPXtvCBOM4TLZzc9UY
@player1username=123
@player1password=123

### Get access token
POST http://localhost:8180/realms/FourteenGames/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{ClientId}}&client_secret={{ClientSecret}}&username={{player1username}}&password={{player1password}}&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token);
%}

### starting a new match
POST http://localhost:8082/go/api/matches
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "size": 19
}

> {%
    client.global.set("gameId", response.body.id);
%}

### getting match
GET http://localhost:8082/go/api/matches/{{gameId}}
Authorization: Bearer {{access_token}}