spring.application.name=go-backend
server.port=8082
ai-catalog-api.url=http://localhost:8000/api/go

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=go
spring.datasource.username=user
spring.datasource.password=password

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.data-locations=classpath:sql/data.sql

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/FourteenGames
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/FourteenGames/protocol/openid-connect/certs

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password


spring.rabbitmq.fourteengames.exchange-name=xivgames_exchange
spring.rabbitmq.fourteengames.register-game-binding=game.register
spring.rabbitmq.fourteengames.register-game-queue=register_game
spring.rabbitmq.fourteengames.unlock-achievement-binding=achievement.unlock
spring.game.registration.internal-game-url=http://localhost:5175/gamehosts/go/
spring.game.registration.external-game-url=http://localhost:5175/gamehosts/go/

spring.game.registration.id=e3b0c442-98fc-4dcb-8b66-3a9c5f993bcd
spring.game.registration.name=Go
spring.game.registration.description=An ancient abstract strategy board game originating from East Asia.
spring.game.registration.max-players=2
spring.game.registration.ai-start-game-endpoint=http://localhost:8082/go/api/matches/ai
spring.game.registration.start-game-endpoint=http://localhost:8082/go/api/matches
spring.game.registration.price=29.99
spring.game.registration.image=https://media.istockphoto.com/id/1286732858/vector/go-game-icon-vector-trendy-flat-go-game-icon-from-sport-collection-isolated-on-white.jpg?s=612x612&w=0&k=20&c=8hO8ahHh2Gtub84Rpy7Vc_rx9OrwFjMEqdGLpdHbYoU=
spring.game.registration.icon=https://static.thenounproject.com/png/5689504-200.png
spring.game.registration.genre=Strategy

cors.allowed-origins=http://localhost:5173,http://localhost:5175